mport logging
import uuid
from typing import List, Union, Optional, Dict, Any
import numpy as np
from fastapi import FastAPI, HTTPException, Body, Path, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, field
validator, Field
_
import brain
class GridInput(BaseModel):
grid
_
data: List[List[Union[int, float]]] = Field(..., example=[[-1, 1,
request
_
id: Optional[str] = None
-1], [2,
-1, 3], [-1, 4,
-1]])
@field
_
validator('grid
_
data')
def validate
_grid
_
data(cls, v: List[List[Union[int, float]]]) -> List[List[Union[int, float]]]:
if not v:
raise ValueError("Grid data cannot be empty.
")
if not all(isinstance(row, list) for row in v):
raise ValueError("Grid data must be a list of lists.
")
if not v[0]:
raise ValueError("Grid rows cannot be empty.
")
num
_
cols = len(v[0])
if num
cols == 0:
_
raise ValueError("Grid columns cannot be empty (first row is empty).
")
if not all(len(row) == num
_
cols for row in v):
raise ValueError("All rows in the grid must have the same number of columns.
")
for r
_
idx, row in enumerate(v):
for c
idx, cell
_
_
val in enumerate(row):
if not isinstance(cell
_
val, (int, float)):
raise ValueError(f"Cell ({r
_
idx},{c
_
idx}) has invalid type: {type(cell
_
val)}. Must be
number.
")
return v
class ScoreOutput(BaseModel):
module
name: str
_
request
_
id: Optional[str]
score
_grid: List[List[float]]
message: Optional[str] = None
error: Optional[str] = None
app = FastAPI(
title="橘子專案 - 自動補格評分API (Júzi Zhuānxàn - Scoring API)"
,
description="提供盤面評分模組的API接口 (Provides API endpoints for grid scoring
modules).
"
,
version="1.0.0"
)
logging.basicConfig(
level=logging.INFO,
format='%(asctime)s - %(levelname)s - %(name)s - MAIN -
%(module)s.%(funcName)s:%(lineno)d - RequestID: %(request
_
id)s - %(message)s'
,
datefmt='%Y-%m-%d %H:%M:%S'
,
)
logger = logging.getLogger(__
name
__)
@app.middleware("http")
async def log_
requests
_
middleware(request: Request, call
_
request
_
id = request.headers.get("X-Request-ID")
if not request
id:
_
request
_
id = str(uuid.uuid4())
next):
request.state.request
_
id = request
_
id
old
_
factory = logging.getLogRecordFactory()
def record
_
factory(*args,
**kwargs):
record = old
_
factory(*args,
**kwargs)
record.request
_
id = request
id
_
return record
logging.setLogRecordFactory(record
_
factory)
logger.info(f"Request received: {request.method} {request.url.path}"
, extra={'request
_
id':
request
_
id})
response = await call
_
next(request)
logger.info(f"Response status: {response.status
_
code}"
, extra={'request
_
id': request
_
logging.setLogRecordFactory(old
_
factory)
return response
id})
@app.post("/score/{module
_
name}"
, response
_
model=ScoreOutput, tags=["Scoring
Modules"])
async def get
scores
for
_
_
_
module(
request: Request,
payload: GridInput,
module
_
name: str = Path(..., description="The name of the scoring module to use.
")
):
req_
id = payload.request
_
id or request.state.request
_
id or str(uuid.uuid4())
logger.info(f"Processing /score/{module
_
name} request.
"
, extra={'request
_
id': req_
id})
if module
name not in brain.REGISTERED
MODULES
BRAIN:
_
_
_
logger.warning(f"Module '{module
_
name}' not found.
"
, extra={'request
_
id': req_
id})
raise HTTPException(status
_
code=404, detail=f"Module '{module
_
name}' not found.
Available modules: {list(brain.REGISTERED
MODULES
_
_
BRAIN.keys())}")
try:
np_grid = np.array(payload.grid
_
data, dtype=np.float32)
if np_grid.size == 0:
logger.warning("Input grid is empty after numpy conversion.
"
, extra={'request
_
id':
req_
id})
raise HTTPException(status
_
code=400, detail="Grid cannot be empty.
")
logger.info(f"Calling brain.get
module
_
_
score for module: {module
_
name}"
,
extra={'request
_
id': req_
id})
score
_
np_
array = brain.get
module
_
_
score(module
_
name, np_grid, request
_
id=req_
id)
score
list
of
lists = score
_
_
_
_
np_
array.tolist()
logger.info(f"Successfully scored grid with module: {module
_
name}"
,
extra={'request
_
id': req_
id})
return ScoreOutput(
module
name=module
name,
_
_
request
_
id=req_
id,
score
_grid=score
list
of
lists,
_
_
_
message=f"Scores successfully generated by module '{module
_
name}'
"
.
)
except ValueError as ve:
logger.error(f"ValueError during scoring for module {module
_
name}: {str(ve)}"
,
extra={'request
_
id': req_
id}, exc
_
info=True)
raise HTTPException(status
_
code=400, detail=f"Error processing grid for module
{module
_
name}: {str(ve)}")
except Exception as e:
logger.error(f"Unexpected error during scoring for module {module
_
name}: {str(e)}"
,
extra={'request
_
id': req_
id}, exc
_
info=True)
raise HTTPException(status
_
code=500, detail=f"An unexpected error occurred while
scoring with module '{module
_
name}'
.
")
@app.get("/modules"
, response
_
model=Dict[str, List[str]], tags=["Utility"])
async def list
available
_
_
modules():
"""Lists all available scoring modules.
"""
return {"available
_
modules": list(brain.REGISTERED
MODULES
_
_
BRAIN.keys())}
@app.get("/"
, tags=["Utility"])
async def root():
"""Root endpoint providing a welcome message.
"""
return {"message": "橘子專案 - 自動補格評分API. Use /docs for API documentation.
"}
if
name
== "
main
":
__
__
import uvicorn
__
__
uvicorn.run(app, host="0.0.0.0"
, port=8000)