# main14.py
"""
FastAPI 主應用：
提供 /predict 介面來預測給定網格中 target 數字最可能所在的 Top-3 遮蔽格位置。
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import numpy as np
import logging
from analyzer11 import collect_all_scores, normalize_tensor, fuse_scores, get_topk_positions

# 設定日誌檔案與級別
logging.basicConfig(
    filename="predict.log",
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s"
)

app = FastAPI()

class PredictRequest(BaseModel):
    grid: list[list[int]]
    target: int

class PredictResponse(BaseModel):
    predictions: list[dict]

@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest):
    grid = request.grid
    target = request.target
    # 驗證輸入網格有效性
    rows = len(grid)
    if rows == 0:
        logging.error("Empty grid received.")
        raise HTTPException(status_code=400, detail="Grid cannot be empty.")
    cols = len(grid[0])
    for row in grid:
        if len(row) != cols:
            logging.error("Non-rectangular grid.")
            raise HTTPException(status_code=400, detail="Grid must be rectangular.")
    if rows > 50 or cols > 50:
        logging.error(f"Grid size {rows}x{cols} exceeds limit.")
        raise HTTPException(status_code=400, detail="Grid size exceeds 50x50 limit.")
    # 驗證資料型別與內容
    for r in range(rows):
        for c in range(cols):
            val = grid[r][c]
            if not isinstance(val, int):
                logging.error("Non-integer value in grid.")
                raise HTTPException(status_code=400, detail="Grid values must be integers.")
            if val != -1 and val <= 0:
                logging.error("Invalid value in grid.")
                raise HTTPException(status_code=400, detail="Grid values must be positive or -1 for blanks.")
    if not isinstance(target, int):
        logging.error("Target is not an integer.")
        raise HTTPException(status_code=400, detail="Target must be an integer.")
    if target <= 0:
        logging.error("Target is not positive.")
        raise HTTPException(status_code=400, detail="Target must be a positive integer.")
    # 驗證唯一性約束
    seen = set()
    for r in range(rows):
        for c in range(cols):
            val = grid[r][c]
            if val != -1:
                if val in seen:
                    logging.error("Duplicate value in grid.")
                    raise HTTPException(status_code=400, detail="Grid contains duplicate values.")
                seen.add(val)
    if target in seen:
        logging.error("Target already present in grid.")
        raise HTTPException(status_code=400, detail="Target number is already in the grid.")
    # 執行預測流程
    try:
        arr = np.array(grid, dtype=int)
        blank_count = int(np.sum(arr == -1))
        logging.info(f"Predict request: target={target}, grid={rows}x{cols}, blanks={blank_count}")
        scores_tensor = collect_all_scores(arr, target)
        if scores_tensor.size == 0:
            raise HTTPException(status_code=500, detail="No scores generated by modules.")
        normalized_tensor = normalize_tensor(scores_tensor, method="minmax")
        fused_scores = fuse_scores(normalized_tensor)
        top_positions = get_topk_positions(fused_scores, arr, k=3)
        # 構造回傳結果（轉換為1-based索引）
        predictions = []
        for (r, c), score in top_positions:
            predictions.append({
                "row": r + 1,
                "col": c + 1,
                "confidence": round(score, 4)
            })
        logging.info(f"Top-3 predictions: {predictions}")
        return {"predictions": predictions}
    except HTTPException as e:
        # 傳遞 HTTPException 錯誤
        raise e
    except Exception as e:
        logging.exception("Unexpected error during prediction.")
        raise HTTPException(status_code=500, detail="Internal server error")