import logging
import uuid
from typing import List, Union, Optional, Dict, Any

import numpy as np
from fastapi import FastAPI, HTTPException, Body, Path, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, field_validator, Field

import brain

class GridInput(BaseModel):
    grid_data: List[List[Union[int, float]]] = Field(..., example=[[-1, 1, -1], [2, -1, 3], [-1, 4, -1]])
    request_id: Optional[str] = None

    @field_validator('grid_data')
    def validate_grid_data(cls, v: List[List[Union[int, float]]]) -> List[List[Union[int, float]]]:
        if not v:
            raise ValueError("Grid data cannot be empty.")
        if not all(isinstance(row, list) for row in v):
            raise ValueError("Grid data must be a list of lists.")
        if not v[0]:
             raise ValueError("Grid rows cannot be empty.")
        num_cols = len(v[0])
        if num_cols == 0:
            raise ValueError("Grid columns cannot be empty (first row is empty).")
        if not all(len(row) == num_cols for row in v):
            raise ValueError("All rows in the grid must have the same number of columns.")
        for r_idx, row in enumerate(v):
            for c_idx, cell_val in enumerate(row):
                if not isinstance(cell_val, (int, float)):
                    raise ValueError(f"Cell ({r_idx},{c_idx}) has invalid type: {type(cell_val)}. Must be number.")
        return v

class ScoreOutput(BaseModel):
    module_name: str
    request_id: Optional[str]
    score_grid: List[List[float]]
    message: Optional[str] = None
    error: Optional[str] = None

app = FastAPI(
    title="橘子專案 - 自動補格評分API (Júzi Zhuānxàn - Scoring API)",
    description="提供盤面評分模組的API接口 (Provides API endpoints for grid scoring modules).",
    version="1.0.0"
)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(name)s - MAIN - %(module)s.%(funcName)s:%(lineno)d - RequestID: %(request_id)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
)
logger = logging.getLogger(__name__)

@app.middleware("http")
async def log_requests_middleware(request: Request, call_next):
    request_id = request.headers.get("X-Request-ID")
    if not request_id:
        request_id = str(uuid.uuid4())
    
    request.state.request_id = request_id

    old_factory = logging.getLogRecordFactory()
    def record_factory(*args, **kwargs):
        record = old_factory(*args, **kwargs)
        record.request_id = request_id
        return record
    logging.setLogRecordFactory(record_factory)
    
    logger.info(f"Request received: {request.method} {request.url.path}", extra={'request_id': request_id})
    
    response = await call_next(request)
    
    logger.info(f"Response status: {response.status_code}", extra={'request_id': request_id})
    logging.setLogRecordFactory(old_factory)
    return response

@app.post("/score/{module_name}", response_model=ScoreOutput, tags=["Scoring Modules"])
async def get_scores_for_module(
    request: Request,
    payload: GridInput,
    module_name: str = Path(..., description="The name of the scoring module to use.")
):
    req_id = payload.request_id or request.state.request_id or str(uuid.uuid4())

    logger.info(f"Processing /score/{module_name} request.", extra={'request_id': req_id})

    if module_name not in brain.REGISTERED_MODULES_BRAIN:
        logger.warning(f"Module '{module_name}' not found.", extra={'request_id': req_id})
        raise HTTPException(status_code=404, detail=f"Module '{module_name}' not found. Available modules: {list(brain.REGISTERED_MODULES_BRAIN.keys())}")

    try:
        np_grid = np.array(payload.grid_data, dtype=np.float32)
        
        if np_grid.size == 0:
            logger.warning("Input grid is empty after numpy conversion.", extra={'request_id': req_id})
            raise HTTPException(status_code=400, detail="Grid cannot be empty.")

        logger.info(f"Calling brain.get_module_score for module: {module_name}", extra={'request_id': req_id})
        score_np_array = brain.get_module_score(module_name, np_grid, request_id=req_id)
        
        score_list_of_lists = score_np_array.tolist()
        
        logger.info(f"Successfully scored grid with module: {module_name}", extra={'request_id': req_id})
        return ScoreOutput(
            module_name=module_name,
            request_id=req_id,
            score_grid=score_list_of_lists,
            message=f"Scores successfully generated by module '{module_name}'."
        )

    except ValueError as ve:
        logger.error(f"ValueError during scoring for module {module_name}: {str(ve)}", extra={'request_id': req_id}, exc_info=True)
        raise HTTPException(status_code=400, detail=f"Error processing grid for module {module_name}: {str(ve)}")
    except Exception as e:
        logger.error(f"Unexpected error during scoring for module {module_name}: {str(e)}", extra={'request_id': req_id}, exc_info=True)
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred while scoring with module '{module_name}'.")


@app.get("/modules", response_model=Dict[str, List[str]], tags=["Utility"])
async def list_available_modules():
    """Lists all available scoring modules."""
    return {"available_modules": list(brain.REGISTERED_MODULES_BRAIN.keys())}

@app.get("/", tags=["Utility"])
async def root():
    """Root endpoint providing a welcome message."""
    return {"message": "橘子專案 - 自動補格評分API. Use /docs for API documentation."}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

